name: Build with LodePNG

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev build-essential

    - name: checkout lode
      run: git submodule update --init --recursive
    - name: create output
      run: mkdir output

    - name: make build LodePNG
      run: make graphics-lode.out
