name: Build with LodePNG

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install General
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libboost-program-options-dev \
            qt6-base-dev \
            libblas-dev \
            libopenblas-dev

      - name: checkout lode
        run: git submodule update --init --recursive

      - name: create output
        run: mkdir output

      - name: make build LodePNG
        run: make graphics-lode.out
